services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - asa-network

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-server
      - asa-server2
      - asa-server3
      - asa-server4
    networks:
      - asa-network

  asa-server:
    build: 
      context: ./asa-server
      dockerfile: Dockerfile
    container_name: asa-server
    networks:
      - asa-network

  asa-server2:
    build: 
      context: ./asa-server2
      dockerfile: Dockerfile
    container_name: asa-server2
    networks:
      - asa-network

  asa-server3:
    build: 
      context: ./asa-server3
      dockerfile: Dockerfile
    container_name: asa-server3
    networks:
      - asa-network

  asa-server4:
    build: 
      context: ./asa-server4
      dockerfile: Dockerfile
    container_name: asa-server4
    networks:
      - asa-network

# Docker Networks
networks:
  asa-network:
    driver: bridge
